### PR TITLE
Release/1230

### PR DESCRIPTION
**Pull request by drizzlezyk**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Review by hdsong2 — APPROVED** [review]
LGTM

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.0
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/b979687f8110427d98af50b2bee900b7">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.0
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/9b957981125847219ef08c28923dcce3">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.0
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/6bdba52bcaea4ddc8479b29d324edf0c">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.0
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/08e4828317874bd191c4933ed72b7a99">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>测试覆盖率</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/cbd64fdc7ac64bb5bae0289cc5fd2766">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.0
%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_测试覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/xihe-server/778/778_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/5c049736c2cd46ba9a4c8bbcbc5e0fca/15efae88e9504a888637b176ff7b11f6">点击跳转</a></td>
</tr>
</table>

**Pull request merged**
